<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8ff36c761159e72d835ee5e29d8f03fe
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Woow\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Woow\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8ff36c761159e72d835ee5e29d8f03fe::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8ff36c761159e72d835ee5e29d8f03fe::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8ff36c761159e72d835ee5e29d8f03fe::$classMap;

        }, null, ClassLoader::class);
    }
}
